
/**
 * This file was auto generated by packages/playground/wordpress/build/build.js
 * DO NOT CHANGE MANUALLY!
 * This file must statically exists in the project because of the way
 * vite resolves imports.
 */
export function getWordPressModuleDetails(wpVersion: string = "6.5"): { size: number, url: string } {
	// no-op for now, we don't want to bundle the whole WordPress with the single executable

	throw new Error('Unsupported WordPress module: ' + wpVersion);
}
