
// @ts-ignore
import url from './sqlite-database-integration.zip?url';

/**
 * This file was auto generated by packages/playground/wordpress-builds/build/refresh-sqlite-integration-plugin.js
 * DO NOT CHANGE MANUALLY!
 * This file must statically exists in the project because of the way
 * vite resolves imports.
 */
export const size = 84294;
export { url };

