// @ts-ignore
import url_develop from './sqlite-database-integration-develop.zip?url';
// @ts-ignore
import url_v2_1_17_alpha_1 from './sqlite-database-integration-v2.1.17-alpha.1.zip?url';

/**
 * This file was auto generated by:
 *   packages/playground/wordpress-builds/build/refresh-sqlite-integration-plugin.js
 * DO NOT CHANGE MANUALLY!
 * This file must statically exists in the project because of the way
 * vite resolves imports.
 */
export const LatestSqliteDriverVersion = 'develop';

export function getSqliteDriverModuleDetails(
	version = LatestSqliteDriverVersion
): {
	size: number;
	url: string;
} {
	switch (version) {
		case 'develop':
			/** @ts-ignore */
			return {
				size: 204336,
				url: url_develop,
			};
		case 'v2.1.17-alpha.1':
			/** @ts-ignore */
			return {
				size: 84618,
				url: url_v2_1_17_alpha_1,
			};
	}
	throw new Error(
		'Unsupported SQLite integration plugin version: ' + version
	);
}
