// @ts-ignore
import url_trunk from './sqlite-database-integration-trunk.zip?url';
// @ts-ignore
import url_v2_1_16 from './sqlite-database-integration-v2.1.16.zip?url';
// @ts-ignore
import url_v2_2_22 from './sqlite-database-integration-v2.2.22.zip?url';
// @ts-ignore
import url_v2_2_22_php56 from './sqlite-database-integration-v2.2.22-php56.zip?url';

/**
 * This file was auto generated by:
 *   packages/playground/wordpress-builds/build/refresh-sqlite-integration-plugin.js
 * DO NOT CHANGE MANUALLY!
 * This file must statically exists in the project because of the way
 * vite resolves imports.
 */
export const LatestSqliteDriverVersion = 'trunk';

export function getSqliteDriverModuleDetails(
	version = LatestSqliteDriverVersion
): {
	size: number;
	url: string;
} {
	switch (version) {
		
		case 'trunk':
			/** @ts-ignore */
			return {
				size: 263816,
				url: url_trunk,
			};
		case 'v2.1.16':
			/** @ts-ignore */
			return {
				size: 84250,
				url: url_v2_1_16,
			};
		case 'v2.2.22':
			/** @ts-ignore */
			return {
				size: 263816,
				url: url_v2_2_22,
			};
		case 'v2.2.22-php56':
			/** @ts-ignore */
			return {
				size: 263749,
				url: url_v2_2_22_php56,
			};
	}
	throw new Error(
		'Unsupported SQLite integration plugin version: ' + version
	);
}
