// @ts-ignore
import url_trunk from './sqlite-database-integration-trunk.zip?url';
// @ts-ignore
import url_v2_1_16 from './sqlite-database-integration-v2.1.16.zip?url';
// @ts-ignore
import url_v3_0_0_rc_3_php52 from './sqlite-database-integration-v3.0.0-rc.3-php52.zip?url';

/**
 * This file was auto generated by:
 *   packages/playground/wordpress-builds/build/refresh-sqlite-integration-plugin.js
 * DO NOT CHANGE MANUALLY!
 * This file must statically exists in the project because of the way
 * vite resolves imports.
 */
export const LatestSqliteDriverVersion = 'trunk';

export function getSqliteDriverModuleDetails(
	version = LatestSqliteDriverVersion
): {
	size: number;
	url: string;
} {
	switch (version) {
		case 'trunk':
			/** @ts-ignore */
			return {
				size: 207811,
				url: url_trunk,
			};
		case 'v2.1.16':
			/** @ts-ignore */
			return {
				size: 84250,
				url: url_v2_1_16,
			};
		case 'v3.0.0-rc.3-php52':
			/** @ts-ignore */
			return {
				size: 210820,
				url: url_v3_0_0_rc_3_php52,
			};
	}
	throw new Error(
		'Unsupported SQLite integration plugin version: ' + version
	);
}
