blank_issues_enabled: true
contact_links:
    - name: Playground Slack Channel
      url: https://wordpress.slack.com/archives/C04EWKGDJ0K
      about: If you have a question, please see our docs or use our Slack community!
