notifications:
    email:
        - helpme+github@gmail.com
language: node_js
dist: trusty
node_js:
    - '8'
    - '10'
    - 'node'
script:
    - npm run lint
    - npm test

after_success:
    - npm install istanbul codecov
    - npm run cover
    - ./node_modules/.bin/codecov

cache:
    directories:
        - node_modules

env:
    global:
        - CODECOV_TOKEN=88ae9a05-ad28-4ce5-baa4-34bb0c4a055c
