/**
 * Generates a random, human readable site name.
 * For example: "Happy Abandoned Road", "Calm Old School", etc.
 */
export function randomSiteName() {
	// The three slots draw from disjoint lists (no word appears in two), so a
	// generated name never repeats a word. Pools are kept generous — small pools
	// made the same word (e.g. "Busy") surface across several names at once.
	const adjectives = [
		'Happy',
		'Sad',
		'Excited',
		'Calm',
		'Brave',
		'Shy',
		'Clever',
		'Funny',
		'Kind',
		'Honest',
		'Loyal',
		'Patient',
		'Creative',
		'Energetic',
		'Ambitious',
		'Generous',
		'Humble',
		'Confident',
		'Curious',
		'Determined',
		'Cheerful',
		'Gentle',
		'Bold',
		'Fearless',
		'Witty',
		'Serene',
		'Playful',
		'Radiant',
		'Mellow',
		'Spirited',
		'Jolly',
		'Nimble',
		'Earnest',
		'Plucky',
		'Dreamy',
		'Lively',
		'Merry',
		'Tranquil',
		'Breezy',
		'Chipper',
	];
	const differentAdjectives = [
		'Abandoned',
		'Old',
		'Sunny',
		'Quiet',
		'Busy',
		'Noisy',
		'Peaceful',
		'Cozy',
		'Modern',
		'Vintage',
		'Classic',
		'Trendy',
		'Hip',
		'Chic',
		'Glamorous',
		'Rustic',
		'Golden',
		'Silver',
		'Crimson',
		'Azure',
		'Emerald',
		'Amber',
		'Velvet',
		'Crystal',
		'Misty',
		'Frosty',
		'Rugged',
		'Hidden',
		'Wild',
		'Ancient',
		'Grand',
		'Silent',
		'Sacred',
		'Hollow',
		'Sleepy',
	];
	const nouns = [
		'Road',
		'School',
		'Village',
		'Town',
		'City',
		'State',
		'Country',
		'Garden',
		'Park',
		'Forest',
		'Mountain',
		'Lake',
		'Ocean',
		'River',
		'Valley',
		'Harbor',
		'Canyon',
		'Bay',
		'Meadow',
		'Summit',
		'Stream',
		'Beach',
		'Hill',
		'Glen',
		'Field',
		'Grove',
		'Cove',
		'Ridge',
		'Prairie',
		'Delta',
		'Lagoon',
		'Marsh',
		'Basin',
		'Plateau',
		'Island',
		'Bluff',
		'Orchard',
		'Cascade',
		'Fjord',
		'Haven',
	];
	return [
		adjectives[Math.floor(Math.random() * adjectives.length)],
		differentAdjectives[
			Math.floor(Math.random() * differentAdjectives.length)
		],
		nouns[Math.floor(Math.random() * nouns.length)],
	].join(' ');
}
