// @ts-ignore
import url_beta from './wp-beta.tar.zst?url';
// @ts-ignore
import url_7_0 from './wp-7.0.tar.zst?url';
// @ts-ignore
import url_6_9 from './wp-6.9.tar.zst?url';
// @ts-ignore
import url_6_8 from './wp-6.8.tar.zst?url';
// @ts-ignore
import url_6_7 from './wp-6.7.tar.zst?url';
// @ts-ignore
import url_6_6 from './wp-6.6.tar.zst?url';
// @ts-ignore
import url_6_5 from './wp-6.5.tar.zst?url';
// @ts-ignore
import url_6_4 from './wp-6.4.tar.zst?url';
// @ts-ignore
import url_6_3 from './wp-6.3.tar.zst?url';

/**
 * This file was auto generated by packages/playground/wordpress-builds/build/build.js
 * and packages/playground/wordpress-builds/build/build-tar-zst.mjs
 * DO NOT CHANGE MANUALLY!
 * This file must statically exists in the project because of the way
 * vite resolves imports.
 */
export interface WordPressModuleDetails {
	/** Archive file format used by the WordPress core bundle. */
	format: 'zip' | 'tar.zst';
	/** Archive container. */
	container: 'zip' | 'tar';
	/** Compression codec used by the archive payload. */
	codec: 'deflate' | 'zstd';
	/** Compressed byte length of the bundle. */
	size: number;
	/** URL (or dev filesystem path) of the bundle. */
	url: string;
	/** SHA-256 of the compressed bundle, when known for committed local bundles. */
	sha256?: string;
	/** Number of regular files in the bundle, when known for committed local bundles. */
	fileCount?: number;
}

export function getWordPressModuleDetails(
	wpVersion: string = "7.0"
): WordPressModuleDetails {
	switch (wpVersion) {
		
		case 'trunk':
			return {
				format: 'zip',
				container: 'zip',
				codec: 'deflate',
				size: 0,
				url: "https://github.com/WordPress/WordPress/archive/refs/heads/master.zip",
			};
			
		case 'beta':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 4888941,
				sha256: "ddb06f004b6b3f6acf474f4d79fec1f6523f4fe821968acccb13028e42d0b2ca",
				fileCount: 1847,
				url: url_beta,
			};
			
		case '7.0':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 4685024,
				sha256: "3f189748907aba3e362d52b29ef225b22c0e6dd131ce95038f4e47639211acaa",
				fileCount: 1812,
				url: url_7_0,
			};
			
		case '6.9':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 4291546,
				sha256: "2e85882163a84f4880dd8a4ff1add93fac2665c567c7acee1cf1ada0ab6eab83",
				fileCount: 1597,
				url: url_6_9,
			};
			
		case '6.8':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 4330126,
				sha256: "d3f54db44abe7eccde8f9423dd07b114eeeebbeaa74e23a3b6df477423c132cf",
				fileCount: 1537,
				url: url_6_8,
			};
			
		case '6.7':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 4301100,
				sha256: "a8e62ab5954d2c5d8988764a2003695bbb10f454aec302512f84b49251410cc7",
				fileCount: 1528,
				url: url_6_7,
			};
			
		case '6.6':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 3440587,
				sha256: "e168601409ee2e9c8a6ee23dd02b8d6909d7c3fa558d1a2c515e544676bfdd27",
				fileCount: 1367,
				url: url_6_6,
			};
			
		case '6.5':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 3384145,
				sha256: "aeba52ae7ef500210e1bdfd449b9a8f14d2f287940b69498b17ca59f78e5e303",
				fileCount: 1359,
				url: url_6_5,
			};
			
		case '6.4':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 3302964,
				sha256: "6e42beec88143447a2f459e803f186a6f05be271af9b927e1a177431292d6356",
				fileCount: 1331,
				url: url_6_4,
			};
			
		case '6.3':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 2172108,
				sha256: "f7b36859f3a6668ea46c9a78e48dc014a0ebfa25cc458bfab4a63615c4654f3b",
				fileCount: 1253,
				url: url_6_3,
			};
			
		case 'nightly':
			return {
				format: 'zip',
				container: 'zip',
				codec: 'deflate',
				size: 0,
				url: "https://github.com/WordPress/WordPress/archive/refs/heads/master.zip",
			};
		
	}
	throw new Error('Unsupported WordPress module: ' + wpVersion);
}
