
// @ts-ignore
import url_beta from './wp-beta.zip?url';
// @ts-ignore
import url_6_8 from './wp-6.8.zip?url';
// @ts-ignore
import url_6_7 from './wp-6.7.zip?url';
// @ts-ignore
import url_6_6 from './wp-6.6.zip?url';
// @ts-ignore
import url_6_5 from './wp-6.5.zip?url';
// @ts-ignore
import url_6_4 from './wp-6.4.zip?url';
// @ts-ignore
import url_6_3 from './wp-6.3.zip?url';

/**
 * This file was auto generated by packages/playground/wordpress-builds/build/build.js
 * DO NOT CHANGE MANUALLY!
 * This file must statically exists in the project because of the way
 * vite resolves imports.
 */
export type WordPressGitDirectory = {
	resource: 'git:directory';
	url: string;
	ref: string;
	refType?: 'branch' | 'tag' | 'commit' | 'refname';
	path?: string;
};

export type WordPressModuleDetails =
	| {
			type: 'zip';
			size: number;
			url: string;
	  }
	| {
			type: 'git';
			size: number;
			gitDirectory: WordPressGitDirectory;
	  };

export function getWordPressModuleDetails(
	wpVersion: string = '6.8'
): WordPressModuleDetails {
	switch (wpVersion) {
		
		case 'trunk':
			return {
				type: 'git',
				size: 0,
				gitDirectory: {
					resource: 'git:directory',
					url: 'https://github.com/WordPress/wordpress.git',
					ref: 'master',
					refType: 'branch',
				},
			};
			
		case 'beta':
			/** @ts-ignore */
			return {
				type: 'zip',
				size: 24775546,
				url: url_beta,
			};
			
		case '6.8':
			/** @ts-ignore */
			return {
				type: 'zip',
				size: 24743772,
				url: url_6_8,
			};
			
		case '6.7':
			/** @ts-ignore */
			return {
				type: 'zip',
				size: 24594721,
				url: url_6_7,
			};
			
		case '6.6':
			/** @ts-ignore */
			return {
				type: 'zip',
				size: 18386194,
				url: url_6_6,
			};
			
		case '6.5':
			/** @ts-ignore */
			return {
				type: 'zip',
				size: 18457511,
				url: url_6_5,
			};
			
		case '6.4':
			/** @ts-ignore */
			return {
				type: 'zip',
				size: 18265208,
				url: url_6_4,
			};
			
		case '6.3':
			/** @ts-ignore */
			return {
				type: 'zip',
				size: 3595053,
				url: url_6_3,
			};
			
		case 'nightly':
			return {
				type: 'git',
				size: 0,
				gitDirectory: {
					resource: 'git:directory',
					url: 'https://github.com/WordPress/wordpress.git',
					ref: 'master',
					refType: 'branch',
				},
			};

	}
	throw new Error('Unsupported WordPress module: ' + wpVersion);
}
