// @ts-ignore
import url_beta from './wp-beta.tar.zst?url';
// @ts-ignore
import url_7_0 from './wp-7.0.tar.zst?url';
// @ts-ignore
import url_6_9 from './wp-6.9.tar.zst?url';
// @ts-ignore
import url_6_8 from './wp-6.8.tar.zst?url';
// @ts-ignore
import url_6_7 from './wp-6.7.tar.zst?url';
// @ts-ignore
import url_6_6 from './wp-6.6.tar.zst?url';
// @ts-ignore
import url_6_5 from './wp-6.5.tar.zst?url';
// @ts-ignore
import url_6_4 from './wp-6.4.tar.zst?url';
// @ts-ignore
import url_6_3 from './wp-6.3.tar.zst?url';

/**
 * This file was auto generated by packages/playground/wordpress-builds/build/build.js
 * and packages/playground/wordpress-builds/build/build-tar-zst.mjs
 * DO NOT CHANGE MANUALLY!
 * This file must statically exists in the project because of the way
 * vite resolves imports.
 */
export interface WordPressModuleDetails {
	/** Archive file format used by the WordPress core bundle. */
	format: 'zip' | 'tar.zst';
	/** Archive container. */
	container: 'zip' | 'tar';
	/** Compression codec used by the archive payload. */
	codec: 'deflate' | 'zstd';
	/** Compressed byte length of the bundle. */
	size: number;
	/** URL (or dev filesystem path) of the bundle. */
	url: string;
	/** SHA-256 of the compressed bundle, when known for committed local bundles. */
	sha256?: string;
	/** Number of regular files in the bundle, when known for committed local bundles. */
	fileCount?: number;
}

export function getWordPressModuleDetails(
	wpVersion: string = "7.0"
): WordPressModuleDetails {
	switch (wpVersion) {
		
		case 'trunk':
			return {
				format: 'zip',
				container: 'zip',
				codec: 'deflate',
				size: 0,
				url: "https://github.com/WordPress/WordPress/archive/refs/heads/master.zip",
			};
			
		case 'beta':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 4671931,
				sha256: "e5045523831af3884c961e33e95fc4f85337b9adf9584de2c4d189ef839d5e78",
				fileCount: 1844,
				url: url_beta,
			};
			
		case '7.0':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 4687384,
				sha256: "76c5b10613edf2d31a521ef269153bc4248fc9bc4ab66634286e3024d6e43495",
				fileCount: 1812,
				url: url_7_0,
			};
			
		case '6.9':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 4292323,
				sha256: "816f9fb2bec46f13334bd15318ce652de3cdc51d7c03076dc546327237100d4b",
				fileCount: 1597,
				url: url_6_9,
			};
			
		case '6.8':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 4331397,
				sha256: "3924929e8f6bcf97e2493ef41c077c2b03a11196cb137034994661ea16c946eb",
				fileCount: 1537,
				url: url_6_8,
			};
			
		case '6.7':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 4301555,
				sha256: "eee1e6b00b3886a6b387229323ee311960ff61502aebdb3ef03e06eb78b4fc87",
				fileCount: 1531,
				url: url_6_7,
			};
			
		case '6.6':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 3440587,
				sha256: "e168601409ee2e9c8a6ee23dd02b8d6909d7c3fa558d1a2c515e544676bfdd27",
				fileCount: 1367,
				url: url_6_6,
			};
			
		case '6.5':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 3384145,
				sha256: "aeba52ae7ef500210e1bdfd449b9a8f14d2f287940b69498b17ca59f78e5e303",
				fileCount: 1359,
				url: url_6_5,
			};
			
		case '6.4':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 3302964,
				sha256: "6e42beec88143447a2f459e803f186a6f05be271af9b927e1a177431292d6356",
				fileCount: 1331,
				url: url_6_4,
			};
			
		case '6.3':
			/** @ts-ignore */
			return {
				format: 'tar.zst',
				container: 'tar',
				codec: 'zstd',
				size: 2172108,
				sha256: "f7b36859f3a6668ea46c9a78e48dc014a0ebfa25cc458bfab4a63615c4654f3b",
				fileCount: 1253,
				url: url_6_3,
			};
			
		case 'nightly':
			return {
				format: 'zip',
				container: 'zip',
				codec: 'deflate',
				size: 0,
				url: "https://github.com/WordPress/WordPress/archive/refs/heads/master.zip",
			};
		
	}
	throw new Error('Unsupported WordPress module: ' + wpVersion);
}
