<?php
/**
 * Autogenerated by reindex_github_ids.php – do not change!
 */

return array (
  'projects' => 
  array (
    'playground_board' => 'PVT_kwDOAAQ2Js4Adkme',
  ),
  'project_id' => 'PVT_kwDOAAQ2Js4Adkme',
  'fields' => 
  array (
    'status' => 
    array (
      'id' => 'PVTSSF_lADOAAQ2Js4AdkmezgTL8Wc',
      'options' => 
      array (
        'inbox' => '4aca50ce',
        'needs_triage_our_reply' => '0b055ebb',
        'needs_authors_reply' => '20567755',
        'up_next' => '08afe404',
        'future_work' => '5d770dea',
        'in_progress' => '47fc9ee4',
        'needs_review' => '4cc61d42',
        'reviewed' => '0f27f789',
        'blocked' => '1effdd50',
        'done' => '98236657',
        'not_doing' => '2a2852fd',
        'project_triage' => '3171d170',
        'on_the_roadmap' => '0480ee83',
        'project_not_now' => 'e0a06684',
        'project_up_soon' => '3ea1bfc9',
        'project_in_progress' => '63a919bb',
        'project_shipped' => 'aff92a27',
      ),
    ),
    'priority' => 
    array (
      'id' => 'PVTSSF_lADOAAQ2Js4AdkmezgTL8bA',
      'options' => 
      array (
        'low' => '620043fc',
        'medium' => 'da944a9c',
        'high' => '0a877460',
        'critical' => '79628723',
        'triage' => 'cc5f4099',
      ),
    ),
    'project' => 
    array (
      'id' => 'PVTSSF_lADOAAQ2Js4Adkmezgccvic',
      'options' => 
      array (
        'offline_support' => '90ba7274',
        'zero_crashes' => '30dc7c82',
        'wordpress_for_docs' => 'dcfe047b',
        'routing' => '76b57c16',
        'playground_on_learn_wordpress_org' => '010e980f',
        'boot_protocol' => 'f7ff8a02',
        'other_task' => 'db7cd0df',
        'documentation_v2' => 'c2eb9f26',
        'php_blueprints' => '5a5cbf79',
      ),
    ),
    'awaiting_authors_reply_' => 
    array (
      'id' => 'PVTSSF_lADOAAQ2Js4AdkmezgcySxY',
      'options' => 
      array (
        'yes' => '6f2db843',
        'no' => '9f7e5343',
      ),
    ),
  ),
);