<?php
/**
 * Autogenerated by reindex_github_ids.php – do not change!
 */

return array (
  'projects' => 
  array (
    'playground_board' => 'PVT_kwDOAAQ2Js4Adkme',
  ),
  'project_id' => 'PVT_kwDOAAQ2Js4Adkme',
  'fields' => 
  array (
    'status' => 
    array (
      'id' => 'PVTSSF_lADOAAQ2Js4AdkmezgTL8Wc',
      'options' => 
      array (
        'future_work' => '5d770dea',
        'needs_triage_our_reply' => '0b055ebb',
        'up_next' => '08afe404',
        'in_progress' => '47fc9ee4',
        'needs_review' => '4cc61d42',
        'reviewed' => '0f27f789',
        'done' => '98236657',
        'not_doing' => '2a2852fd',
        'needs_authors_reply' => '20567755',
        'big_pile_of_projects' => '3171d170',
        'on_the_roadmap' => '0480ee83',
      ),
    ),
    'priority' => 
    array (
      'id' => 'PVTSSF_lADOAAQ2Js4AdkmezgTL8bA',
      'options' => 
      array (
        'low' => '620043fc',
        'medium' => 'da944a9c',
        'high' => '0a877460',
        'critical' => '79628723',
        'triage' => 'cc5f4099',
      ),
    ),
  ),
);