/**
 * This file lives outside of the `src/wordpress` directory on
 * purpose.
 *
 * `src/wordpress` hosts autogenerated code and is added to eslint
 * and NX ignore lists. However, this test file is written by hand
 * and should still be linted and picked up by the test runner.
 */

import { getWordPressModuleDetails } from './wordpress/get-wordpress-module-details';

describe('getWordPressModuleDetails()', () => {
	it('returns ZIP metadata for released versions', () => {
		const module = getWordPressModuleDetails();
		expect(module.type).toBe('zip');
		if (module.type === 'zip') {
			expect(module.url).toMatch(/\/wp-\d\.\d\.zip$/);
		}
	});

	it('returns git metadata for trunk', () => {
		const module = getWordPressModuleDetails('trunk');
		expect(module.type).toBe('git');
		if (module.type === 'git') {
			expect(module.gitDirectory.url).toContain(
				'github.com/WordPress/wordpress.git'
			);
		}
	});
});
